version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_test_app
        container_name: laravel_test_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel_test_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - laravel_network

    web:
        image: nginx:alpine
        container_name: laravel_test_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: laravel_db_test
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_test_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin
        container_name: laravel_phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db  # MySQL sunucusunun adı
            PMA_USER: root  # Kullanıcı adı
            PMA_PASSWORD: root  # Kullanıcı şifresi
        networks:
            - laravel_network
        depends_on:
            - db  # phpMyAdmin, MySQL servisine bağlı

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
        driver: local
